apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: backend
    count: 1

patches:
  - target:
      kind: Deployment
      name: backend
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
      spec:
        template:
          spec:
            securityContext:
              runAsNonRoot: false
            containers:
              - name: backend
                securityContext:
                  readOnlyRootFilesystem: false
