apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - name: ai-agent
    count: 1

patches:
  - target:
      kind: Deployment
      name: ai-agent
    patch: |
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: ai-agent
      spec:
        template:
          spec:
            securityContext:
              runAsNonRoot: false
            containers:
              - name: ai-agent
                securityContext:
                  readOnlyRootFilesystem: false
